// Generated by Wrangler on Sat May 04 2024 22:24:33 GMT-0400 (Chile Standard Time)
// by running `wrangler types`

interface Env {
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	AUTH_SECRET: string;
	AUTH_TRUST_HOST: string;
}
